//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Manually created based on AHS WSDL
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhsServiceReference
{
    using System.ServiceModel;
    using System.Xml.Serialization;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://tempuri.org/", ConfigurationName = "AhsServiceReference.AutoHoldingSoap")]
    public interface AutoHoldingSoap
    {
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/SliderCheck2", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SliderCheck2(string holder, string operation, bool checkExist);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/SliderCheck2", ReplyAction = "*")]
        System.Threading.Tasks.Task<string> SliderCheck2Async(string holder, string operation, bool checkExist);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/CheckHold", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string CheckHold(string holder, string currentOp);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/CheckHold", ReplyAction = "*")]
        System.Threading.Tasks.Task<string> CheckHoldAsync(string holder, string currentOp);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AutoHoldingSoapChannel : AhsServiceReference.AutoHoldingSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutoHoldingSoapClient : System.ServiceModel.ClientBase<AhsServiceReference.AutoHoldingSoap>, AhsServiceReference.AutoHoldingSoap
    {
        public AutoHoldingSoapClient()
        {
        }

        #if !NETCOREAPP  // problematic code on BUILD
        public AutoHoldingSoapClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public AutoHoldingSoapClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public AutoHoldingSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }
        #endif

        public AutoHoldingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public string SliderCheck2(string holder, string operation, bool checkExist)
        {
            return base.Channel.SliderCheck2(holder, operation, checkExist);
        }

        public System.Threading.Tasks.Task<string> SliderCheck2Async(string holder, string operation, bool checkExist)
        {
            return base.Channel.SliderCheck2Async(holder, operation, checkExist);
        }

        public string CheckHold(string holder, string currentOp)
        {
            return base.Channel.CheckHold(holder, currentOp);
        }

        public System.Threading.Tasks.Task<string> CheckHoldAsync(string holder, string currentOp)
        {
            return base.Channel.CheckHoldAsync(holder, currentOp);
        }
    }
}
